/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.bankingclient;

import com.mycompany.bankingclient.models.BankAccount;
import com.mycompany.bankingclient.models.Customer;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Home.java
 * 
 * @reference https://www.youtube.com/watch?v=RDUPOnXCmuw&feature=youtu.be
 * @author Jun Hsin Lim, 16123107
 * @author Jessica Valeria, 16118677
 */
public class Home extends javax.swing.JFrame {

    List<BankAccount> accountList; //arrayList to hold lists of accounts 
    Customer customer;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /*
        * @reference https://www.youtube.com/watch?v=RDUPOnXCmuw&feature=youtu.be
    */
    public void setCustomer(Customer customer) {
        this.customer = customer;
        userName.setText(customer.getFullName()); //change userName label to the customer's fullName
        
        //call GET method customerAccounts through the RESTConnection to retrieve accountList
        accountList = RESTConnection.customerAccounts(customer);
        if(!accountList.isEmpty()){ //check if accountList is empty, "if accountList is NOT empty..."
            Object[] columnNames = {"AId", "Account Type", "Balance"}; //create object array columnNames to hold column names for the table
            DefaultTableModel model = new DefaultTableModel(new Object[0][0], columnNames); //2D objectarray because table is rows and columns
            for (BankAccount al : accountList){ //go through the accountList
                Object[] o = new Object[3]; //create a new object array with 3 index for the 3 columns
                o[0] = al.getAId(); //insert AId into the first column
                o[1] = al.getAccountType(); //insert AccountType into the second column
                o[2] = al.getBalance(); //insert Balance into the third column
                model.addRow(o); //add the object as a new row in model
            }
            accountBalance.setModel(model); //display the model from the above loop in the table in the GUI (accountBalance) 
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BankName = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        WelcomeMsg = new javax.swing.JLabel();
        createAcc = new javax.swing.JButton();
        makeTrans = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountBalance = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BankName.setFont(new java.awt.Font("Castellar", 1, 36)); // NOI18N
        BankName.setText("JJ's Bank");

        userName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        userName.setText("UserName");

        WelcomeMsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        WelcomeMsg.setText("What would you like to do today?");

        createAcc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        createAcc.setText("Create New Account");
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });

        makeTrans.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        makeTrans.setText("Make a Transaction");
        makeTrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeTransActionPerformed(evt);
            }
        });

        accountBalance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "AId", "Account Type", "Balance"
            }
        ));
        jScrollPane1.setViewportView(accountBalance);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BankName)
                            .addComponent(userName))
                        .addGap(0, 183, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(WelcomeMsg))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createAcc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(makeTrans, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BankName)
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(WelcomeMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(createAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(makeTrans)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed
        CreateAccount create = new CreateAccount(); //go to CreateAccount GUI
        create.setCustomer(customer); //pass customer over to the setCustomer method
        create.setVisible(true);
        dispose();
    }//GEN-LAST:event_createAccActionPerformed

    private void makeTransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeTransActionPerformed
        MakeTransaction trans = new MakeTransaction(); //go to MakeTransaction GUI
        trans.setCustomer(customer);
        trans.setAccountList(accountList); //pass accountList to the setAccountList method
        trans.setVisible(true);
        dispose();
    }//GEN-LAST:event_makeTransActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BankName;
    private javax.swing.JLabel WelcomeMsg;
    private javax.swing.JTable accountBalance;
    private javax.swing.JButton createAcc;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeTrans;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables
}
